import { FormEvent, useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { getRevisionSummary, getSubjects } from "../lib/api";
import type { RevisionSummaryRequest, RevisionSummaryResponse, Subject } from "../types/api";
const StudyTipsPage = () => {
  const [subjectId, setSubjectId] = useState<string>("");
  const [notes, setNotes] = useState<string>("");
  const [style, setStyle] = useState<RevisionSummaryRequest["style"]>("bullet");
  const { data: subjects } = useQuery<Subject[]>({ queryKey: ["subjects"], queryFn: () => getSubjects() });
  const mutation = useMutation<RevisionSummaryResponse, Error, RevisionSummaryRequest>({ mutationFn: (payload) => getRevisionSummary(payload) });
  const handleSubmit = (e: FormEvent) => { e.preventDefault(); if (!subjectId || !notes.trim()) { return; } mutation.mutate({ subjectId, text: notes, style }); };
  return (<div className="space-y-6"><div><h2 className="text-xl font-semibold text-text">Revision summary</h2><p className="text-sm text-muted">Turn raw notes into focused summaries and key points.</p></div><form onSubmit={handleSubmit} className="space-y-4 rounded-lg border border-border bg-card/80 p-4"><div className="grid gap-4 md:grid-cols-3"><div className="flex flex-col gap-1"><label className="text-xs font-medium text-muted" htmlFor="subject">Subject</label><select id="subject" className="rounded-md border border-border bg-background px-3 py-2 text-sm text-text" value={subjectId} onChange={(e) => setSubjectId(e.target.value)}><option value="">Select subject</option>{subjects?.map((s) => (<option key={s.id} value={s.id}>{s.name}</option>))}</select></div><div className="flex flex-col gap-1"><label className="text-xs font-medium text-muted" htmlFor="style">Summary style</label><select id="style" className="rounded-md border border-border bg-background px-3 py-2 text-sm text-text" value={style} onChange={(e) => setStyle(e.target.value as RevisionSummaryRequest["style"])}><option value="concise">Concise</option><option value="detailed">Detailed</option><option value="bullet">Bullet points</option></select></div></div><div className="flex flex-col gap-1"><label className="text-xs font-medium text-muted" htmlFor="notes">Notes</label><textarea id="notes" className="h-40 rounded-md border border-border bg-background px-3 py-2 text-sm text-text" value={notes} onChange={(e) => setNotes(e.target.value)} placeholder="Paste the material you want summarized..." /></div><button type="submit" disabled={mutation.isLoading} className="rounded-md bg-primary px-4 py-2 text-sm font-medium text-white hover:bg-primary/90 disabled:opacity-60">{mutation.isLoading ? "Summarizing..." : "Get summary"}</button>{mutation.isError && (<p className="rounded-md border border-red-300 bg-red-50 px-3 py-2 text-xs text-red-700">{mutation.error.message}</p>)}</form>{mutation.data && (<section className="space-y-3 rounded-lg border border-border bg-card/80 p-4 text-sm"><h3 className="text-sm font-semibold text-text">Summary</h3><p className="whitespace-pre-line text-text">{mutation.data.summary}</p>{mutation.data.keyPoints && mutation.data.keyPoints.length > 0 && (<div><h4 className="mt-3 text-xs font-semibold uppercase tracking-wide text-muted">Key points</h4><ul className="mt-1 list-disc space-y-1 pl-5">{mutation.data.keyPoints.map((point) => (<li key={point} className="text-sm text-text">{point}</li>))}</ul></div>)}</section>)}</div>);
};
export default StudyTipsPage;